### ISSUE TITLE
Add `io.Reader` support

### ISSUE THREAD

**Issue by dwisiswant0** [nekrassov01/access-log-parser#1]
Hey @nekrassov01,

First of all, your project is dope!

I used to utilize with [gonx](https://github.com/satyrius/gonx) before, because it was easy to work with. The smooth transformation of `$label` [format](https://github.com/satyrius/gonx?tab=readme-ov-file#format) into regEx made it super user-friendly.

Any chance you could add support for `io.Reader` to pull in log `Data`? Or maybe introduce a new API for `ParseStdin`?
I'm thinking of revamping [teler IDS](https://github.com/kitabisa/teler) using this library, and I've already started reworking it from scratch[^1].

Thanks!
dw1

[^1]: https://groups.google.com/g/teler-announce/c/Fm8Yjh_4of0

**Comment by nekrassov01** [comment]
Thank you.

Yes, I knew it would be nice to have the ability to parse logs in real time, and I was planning on doing that eventually.

I haven't figured out how I'm going to design it yet, but I'm going to get to it in between other projects.

**Comment by nekrassov01** [comment]
@dwisiswant0 

[A new version](https://github.com/nekrassov01/access-log-parser/tree/develop) of this module is almost complete.

Most of my concerns have been revamped.
However, there are a number of changes to method signatures.
Also, the [Parse](https://github.com/nekrassov01/access-log-parser/blob/develop/parser_core.go#L65) method now assumes stream processing.

If it looks OK after using it for a while, I will merge it.

**Comment by nekrassov01** [comment]
@dwisiswant0

I've been making quite a few changes for a while, but I've found a compromise and have merged them into main and released [0.0.18](https://github.com/nekrassov01/access-log-parser/releases/tag/v0.0.18).

I would be happy to have my code incorporated, so please use it!

**Comment by dwisiswant0** [comment]
Thank you for your efforts in getting my request done, @nekrassov01 - I really appreciate it!
